grpc:
  port: 44044
  timeout: 10h

db:
  url: "postgres://admin:123@postgres:5432/shortener_db?sslmode=disable"

http:
  address: "http://localhost:8080"

redis:
  addr: "redis:6379"
  password: "123"